questions = {
    (1, "Science"): (
        "What planet is known as the Red Planet?",
        ["Earth", "Mars", "Venus", "Jupiter"],
        "Mars",
        "Mars is called the Red Planet due to its reddish appearance caused by iron oxide on its surface.",
        "easy",
    ),
    (2, "History"): (
        "What year did World War II end?",
        ["1942", "1945", "1948", "1950"],
        "1945",
        "World War II ended in 1945 after the surrender of Axis powers.",
        "medium",
    ),
    (3, "Math"): (
        "What is 15% of 200?",
        ["25", "30", "35", "40"],
        "30",
        "15% of 200 is 30 (0.15 x 200 = 30).",
        "easy",
    ),
    (4, "Literature"): (
        "Who wrote 'Pride and Prejudice'?",
        ["Charlotte Bronte", "Jane Austen", "Emily Dickinson", "George Eliot"],
        "Jane Austen",
        "'Pride and Prejudice' is a classic novel by Jane Austen, first published in 1813.",
        "easy",
    ),
    (5, "Geography"): (
        "What is the capital of Australia?",
        ["Sydney", "Melbourne", "Canberra", "Brisbane"],
        "Canberra",
        "Canberra was selected as the capital of Australia in 1908.",
        "easy",
    ),
    (6, "Science"): (
        "What is the chemical symbol for gold?",
        ["Ag", "Au", "Fe", "Pt"],
        "Au",
        "Gold's chemical symbol, 'Au,' is derived from its Latin name, aurum.",
        "medium",
    ),
    (7, "History"): (
        "Who was the Emperor of France during the Battle of Waterloo?",
        ["Napoleon Bonaparte", "Louis XVI", "Charlemagne", "Henry IV"],
        "Napoleon Bonaparte",
        "Napoleon Bonaparte was defeated at the Battle of Waterloo in 1815.",
        "medium",
    ),
    (8, "Math"): (
        "Solve: 5 + (8 x 3)",
        ["24", "29", "33", "39"],
        "29",
        "Following order of operations (PEMDAS), 8 x 3 = 24, and 5 + 24 = 29.",
        "easy",
    ),
    (9, "Technology"): (
        "What does 'HTTP' stand for?",
        ["HyperText Transfer Protocol", "High-Tech Transmission Process", "Hyperlink Transfer Program", "High Transfer Protocol"],
        "HyperText Transfer Protocol",
        "HTTP is the foundation of data communication for the World Wide Web.",
        "medium",
    ),
    (10, "Art"): (
        "Who painted the Mona Lisa?",
        ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"],
        "Leonardo da Vinci",
        "Leonardo da Vinci painted the Mona Lisa during the Italian Renaissance.",
        "easy",
    ),
    (11, "Geography"): (
        "Which desert is the largest in the world?",
        ["Sahara", "Gobi", "Arctic", "Antarctic"],
        "Antarctic",
        "The Antarctic Desert is the largest desert, covering about 14 million square kilometers.",
        "hard",
    ),
    (12, "Music"): (
        "Who composed the 'Fifth Symphony'?",
        ["Mozart", "Beethoven", "Bach", "Tchaikovsky"],
        "Beethoven",
        "Ludwig van Beethoven composed the famous 'Fifth Symphony' in C minor.",
        "medium",
    ),
    (13, "Science"): (
        "What is the powerhouse of the cell?",
        ["Nucleus", "Mitochondria", "Ribosome", "Golgi apparatus"],
        "Mitochondria",
        "Mitochondria generate energy for cellular functions.",
        "easy",
    ),
    (14, "History"): (
        "Who was the first woman to win a Nobel Prize?",
        ["Marie Curie", "Rosalind Franklin", "Ada Lovelace", "Dorothy Hodgkin"],
        "Marie Curie",
        "Marie Curie won the Nobel Prize in Physics in 1903.",
        "medium",
    ),
    (15, "Sports"): (
        "Which country has won the most FIFA World Cup titles?",
        ["Germany", "Italy", "Brazil", "Argentina"],
        "Brazil",
        "Brazil has won the FIFA World Cup five times.",
        "easy",
    ),
}
questions.update({
    (16, "Astronomy"): (
        "What is the largest planet in our solar system?",
        ["Earth", "Jupiter", "Saturn", "Neptune"],
        "Jupiter",
        "Jupiter is the largest planet, with a diameter of about 142,984 km.",
        "easy",
    ),
    (17, "Philosophy"): (
        "Who is known as the father of modern philosophy?",
        ["Aristotle", "Socrates", "René Descartes", "Immanuel Kant"],
        "René Descartes",
        "René Descartes is often considered the father of modern philosophy for his statement 'Cogito, ergo sum' ('I think, therefore I am').",
        "medium",
    ),
    (18, "Pop Culture"): (
        "Who directed the movie 'Inception'?",
        ["Christopher Nolan", "Steven Spielberg", "Quentin Tarantino", "James Cameron"],
        "Christopher Nolan",
        "Christopher Nolan directed 'Inception,' a sci-fi thriller released in 2010.",
        "easy",
    ),
    (19, "Economics"): (
        "What does GDP stand for?",
        ["Gross Domestic Product", "Global Development Plan", "Government-Driven Policy", "General Demographic Projection"],
        "Gross Domestic Product",
        "GDP measures the total value of goods and services produced in a country.",
        "medium",
    ),
    (20, "Science"): (
        "What gas do plants absorb during photosynthesis?",
        ["Oxygen", "Nitrogen", "Carbon dioxide", "Methane"],
        "Carbon dioxide",
        "Plants absorb carbon dioxide and release oxygen during photosynthesis.",
        "easy",
    ),
    (21, "Geography"): (
        "Which river is the longest in the world?",
        ["Amazon", "Nile", "Yangtze", "Mississippi"],
        "Nile",
        "The Nile River is traditionally considered the longest, at about 6,650 km.",
        "medium",
    ),
    (22, "Technology"): (
        "Who is known as the father of computers?",
        ["Charles Babbage", "Alan Turing", "John von Neumann", "Ada Lovelace"],
        "Charles Babbage",
        "Charles Babbage conceptualized the first mechanical computer.",
        "medium",
    ),
    (23, "Literature"): (
        "What is the title of the first Harry Potter book?",
        ["The Chamber of Secrets", "The Philosopher's Stone", "The Goblet of Fire", "The Half-Blood Prince"],
        "The Philosopher's Stone",
        "The first book in the Harry Potter series is 'Harry Potter and the Philosopher's Stone' (or 'Sorcerer's Stone' in the U.S.).",
        "easy",
    ),
    (24, "History"): (
        "Which ancient civilization built the Machu Picchu complex?",
        ["Aztecs", "Mayans", "Incas", "Olmecs"],
        "Incas",
        "Machu Picchu was built by the Inca Empire in the 15th century.",
        "medium",
    ),
    (25, "Math"): (
        "What is the value of pi (π) up to two decimal places?",
        ["3.12", "3.14", "3.16", "3.18"],
        "3.14",
        "Pi (π) is approximately equal to 3.14.",
        "easy",
    ),
    (26, "Music"): (
        "Which band released the album 'Abbey Road'?",
        ["The Rolling Stones", "The Beatles", "Pink Floyd", "Led Zeppelin"],
        "The Beatles",
        "'Abbey Road' is one of the most iconic albums by The Beatles.",
        "medium",
    ),
    (27, "Sports"): (
        "How many players are there in a standard basketball team on the court?",
        ["5", "7", "11", "15"],
        "5",
        "Each basketball team fields five players on the court at a time.",
        "easy",
    ),
    (28, "Art"): (
        "What is the art movement associated with Salvador Dalí?",
        ["Impressionism", "Cubism", "Surrealism", "Expressionism"],
        "Surrealism",
        "Salvador Dalí was a prominent figure in the Surrealist art movement.",
        "medium",
    ),
    (29, "Science"): (
        "What part of the human body is affected by conjunctivitis?",
        ["Lungs", "Skin", "Eyes", "Ears"],
        "Eyes",
        "Conjunctivitis, also known as pink eye, affects the eyes.",
        "easy",
    ),
    (30, "Astronomy"): (
        "What type of celestial body is the Sun?",
        ["Planet", "Moon", "Star", "Asteroid"],
        "Star",
        "The Sun is a star at the center of our solar system.",
        "easy",
    ),
    (31, "Philosophy"): (
        "What is the study of being and existence called?",
        ["Epistemology", "Aesthetics", "Ethics", "Ontology"],
        "Ontology",
        "Ontology is the branch of philosophy concerned with the nature of being and existence.",
        "hard",
    ),
    (32, "History"): (
        "Who discovered the Americas in 1492?",
        ["Vasco da Gama", "Christopher Columbus", "Ferdinand Magellan", "Amerigo Vespucci"],
        "Christopher Columbus",
        "Christopher Columbus reached the Americas in 1492, believing he had found a new route to Asia.",
        "easy",
    ),
    (33, "Economics"): (
        "Which economic theory advocates minimal government intervention?",
        ["Keynesian economics", "Supply-side economics", "Laissez-faire economics", "Monetarism"],
        "Laissez-faire economics",
        "Laissez-faire economics promotes minimal government intervention in markets.",
        "medium",
    ),
    (34, "Pop Culture"): (
        "Which TV series features the character Walter White?",
        ["Breaking Bad", "The Wire", "Game of Thrones", "Stranger Things"],
        "Breaking Bad",
        "Walter White is the protagonist of the TV series 'Breaking Bad.'",
        "easy",
    ),
    (35, "Technology"): (
        "What is the name of Apple's voice assistant?",
        ["Alexa", "Cortana", "Siri", "Google Assistant"],
        "Siri",
        "Siri is the virtual assistant developed by Apple.",
        "easy",
    ),
})
questions.update({
    (36, "Indian Mythology"): (
        "Who is the preserver in the Hindu Trinity (Trimurti)?",
        ["Brahma", "Shiva", "Vishnu", "Indra"],
        "Vishnu",
        "Vishnu is regarded as the preserver in the Trimurti, responsible for maintaining balance in the universe.",
        "medium",
    ),
    (37, "Romance Literature"): (
        "Who wrote the famous romantic novel 'Romeo and Juliet'?",
        ["William Shakespeare", "Jane Austen", "Emily Brontë", "Charlotte Brontë"],
        "William Shakespeare",
        "'Romeo and Juliet' is one of Shakespeare's most celebrated works, depicting a tragic love story.",
        "easy",
    ),
    (38, "Sexy Romance"): (
        "Which novel series begins with 'Fifty Shades of Grey'?",
        ["After", "Twilight", "Fifty Shades", "Beautiful Disaster"],
        "Fifty Shades",
        "The 'Fifty Shades' series by E.L. James explores themes of romance and sensuality.",
        "easy",
    ),
    (39, "Indian Mythology"): (
        "What epic features the battle between the Pandavas and Kauravas?",
        ["Ramayana", "Mahabharata", "Bhagavad Gita", "Puranas"],
        "Mahabharata",
        "The Mahabharata narrates the epic war of Kurukshetra between the Pandavas and Kauravas.",
        "easy",
    ),
    (40, "Romantic Movies"): (
        "Which movie features the iconic line, 'You had me at hello'?",
        ["Titanic", "Jerry Maguire", "The Notebook", "Pretty Woman"],
        "Jerry Maguire",
        "'You had me at hello' is a famous line from the romantic drama 'Jerry Maguire.'",
        "medium",
    ),
    (41, "Indian Mythology"): (
        "Who is the consort of Lord Shiva?",
        ["Saraswati", "Lakshmi", "Parvati", "Radha"],
        "Parvati",
        "Parvati, also known as Shakti, is the divine consort of Lord Shiva.",
        "medium",
    ),
    (42, "Romance Novels"): (
        "In 'Pride and Prejudice,' who is Elizabeth Bennet's love interest?",
        ["Mr. Collins", "Mr. Bingley", "Mr. Darcy", "Mr. Wickham"],
        "Mr. Darcy",
        "Elizabeth Bennet and Mr. Darcy are the central romantic leads in Jane Austen's novel.",
        "easy",
    ),
    (43, "Indian Mythology"): (
        "What is the name of the demon king slain by Lord Rama in the Ramayana?",
        ["Kumbhakarna", "Ravana", "Duryodhana", "Shurpanakha"],
        "Ravana",
        "Ravana, the ten-headed king of Lanka, was defeated by Lord Rama in the Ramayana.",
        "easy",
    ),
    (44, "Pop Culture"): (
        "Which popular singer is known as the 'Queen of Pop'?",
        ["Madonna", "Lady Gaga", "Beyoncé", "Rihanna"],
        "Madonna",
        "Madonna is often referred to as the 'Queen of Pop' for her impact on the music industry.",
        "medium",
    ),
    (45, "Sexy Romance"): (
        "Who are the main characters in the romantic series 'After'?",
        ["Tessa and Hardin", "Edward and Bella", "Ana and Christian", "Will and Lou"],
        "Tessa and Hardin",
        "The 'After' series by Anna Todd follows the tumultuous romance of Tessa and Hardin.",
        "medium",
    ),
    (46, "Indian Mythology"): (
        "Which sacred text is a conversation between Arjuna and Krishna?",
        ["Upanishads", "Vedas", "Bhagavad Gita", "Ramayana"],
        "Bhagavad Gita",
        "The Bhagavad Gita is part of the Mahabharata and contains a dialogue between Krishna and Arjuna.",
        "easy",
    ),
    (47, "Romantic Movies"): (
        "Which romantic film features the characters Jack and Rose?",
        ["Pretty Woman", "Titanic", "The Notebook", "A Walk to Remember"],
        "Titanic",
        "Jack and Rose's love story unfolds aboard the ill-fated RMS Titanic.",
        "easy",
    ),
    (48, "Indian Mythology"): (
        "What is the name of Krishna's childhood village?",
        ["Mathura", "Vrindavan", "Hastinapur", "Ayodhya"],
        "Vrindavan",
        "Vrindavan is where Lord Krishna spent much of his childhood and performed divine pastimes.",
        "medium",
    ),
    (49, "Romantic Poetry"): (
        "Who wrote the line, 'How do I love thee? Let me count the ways'?",
        ["William Wordsworth", "Elizabeth Barrett Browning", "Emily Dickinson", "John Keats"],
        "Elizabeth Barrett Browning",
        "This line is from Elizabeth Barrett Browning's famous sonnet 'Sonnet 43.'",
        "medium",
    ),
    (50, "Sexy Romance"): (
        "Which actor played Christian Grey in the 'Fifty Shades' film series?",
        ["Robert Pattinson", "Jamie Dornan", "Ryan Gosling", "Chris Hemsworth"],
        "Jamie Dornan",
        "Jamie Dornan portrayed Christian Grey in the 'Fifty Shades' films.",
        "easy",
    ),
})

